BostonTuts/website/music/urls.py
from django.conf.urls import url
from . import views	

app_name='music'

urlpatterns=[
	# /music/
	url(r'^$',views.index,name='index'),

	#/music/<id#>/
	url(r'^(?P<album_id>[0-9]+)/$',views.detail, name = 'detail'),

	#/music/<id#>/favourite
	url(r'^(?P<album_id>[0-9]+)/favourite/$',views.favourite, name = 'favourite')
]

BostonTuts/website/website/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

BostonTuts/website/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)

	def __str__(self):
		return self.album_title + ' - ' + self.artist


class Song(models.Model):
	album = models.ForeignKey(Album, on_delete = models.CASCADE)
	file_type = models.CharField(max_length = 10)
	song_title = models.CharField(max_length = 250)
	is_favourite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title
		

BostonTuts/website/music/views.py
from django.views import generic
from .models import Album

class IndexView(generic.ListView):
	template_name = 'music/index.html'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/index.html'
	"""docstring for DetailView"generic.DetailViewf 
	model = Album
	template_name = 'music/index.html'__init__(self, arg):
		super(DetailView,generic.DetailView._
		model = Album
		template_name = 'music/index.html'_init__()
		self.arg = arg
		

# # from django.http import Http404
# # from django.shortcuts import render
# from django.shortcuts import render , get_object_or_404
# from .models import Album
# # Create your views here.


# def index(request) :
# 	all_albums = Album.objects.all()
# 	return render(request,'music/index.html',{'all_albums':all_albums})

# def detail(request , album_id):
# 	# try :
# 	# 	album = Album.objects.get(pk=album_id)
# 	# except :
# 	# 	raise Http404("Album doesn't exist!")
# 	album = get_object_or_404(Album,pk= album_id)
# 	return render(request,'music/detail.html',{'album':album})

# def favourite(request,album_id):
# 	album = get_object_or_404(Album,pk = album_id)
# 	try:
# 		selected_song = album.song_set.get(pk=request.POST['song'])
# 	except (KeyError, Song.DoesNotExist):
# 		return render(request, 'music/detail.html',{
# 			'album':album,
# 			'error_message':"You didn't select a valid song"
# 			})
# 	else:
# 		selected_song.is_favourite = True
# 		selected_song.save()
# 		return render(request,'music/detail.html',{'album':album})

BostonTuts/website/music/templates/music/base.html
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
</head>
<body>
	<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- Header -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a clas="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
		</div>
		<!-- Item -->
		<div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Songs
					</a>
				</li>
			</ul>

			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="from-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
					</a>
				</li>
			</ul>
		</div>

	</div>
</nav>
{%block body%}
{%endblock%}
</body>
</html>

BostonTuts/website/music/templates/music/detail.html
{%extends 'music/base.html'%}

{%block body%}
<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}


<form action="{% url 'music:favourite' album.id %}" method="post">
	{% csrf_token %}
	{% for song in album.song_set.all%}
		<input type="radio" id="song{{forloop.counter}}"
		 name="song" value="{{song.id}}"/>
		<label for="song{{forloop.counter}}">
			{{song.song_title}}
			{% if song.is_favourite %}
				<img src="http://i.imgur.com/grdpiDu.gif?1">
			{% endif %}
		</label><br>
	{% endfor %}
	<input type="submit" value="Favourite">
</form>
{%endblock%}

<!-- <ul>
	{% for song in album.song_set.all%}
		<li>{{song.song_title}} - {{song.file_type}}</li>
	{% endfor %}
</ul>
 -->

BostonTuts/website/music/templates/music/index.html
{%extends 'music/base.html'%}

{%block body%}

{% if all_albums %}
	<h3>Here are all my Albums!</h3>
	<ul>
		{% for album in all_albums %}
			<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a> </li>
		{% endfor %}
	</ul>
{% else %}
	<h3>You don't have any albums</h3>
{% endif %}
{%endblock%}
<!-- {% if all_albums %}
	<h3>Here are all my Albums!</h3>
	<ul>
		{% for album in all_albums %}
		<li><a href="/music/{{ album.id }}">{{ album.album_title }}</a> </li>
		{% endfor %}
	</ul>
{% else %}
	<h3>You don't have any albums</h3>
{% endif %} -->